tls:
  certificates:
    - certFile: /certs/xxyyzz.localhost.pem
      keyFile: /certs/xxyyzz.localhost-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/xxyyzz.localhost.pem
        keyFile: /certs/xxyyzz.localhost-key.pem
